server {
  listen 80;
  server_name _;

  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html;
  }

  # Automatically route Docker host IP to machine IP
  resolver 127.0.0.11 valid=30s;
  set $backend_host http://host.docker.internal;

  location /api {
    proxy_pass $backend_host:8080;
  }
}
